version: 2

updates:
  # Maintain dependencies for android packages
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    # Disable version updates for android dependencies
    # This option has no impact on security updates, which have a separate, internal limit of ten open pull requests.
    open-pull-requests-limit: 0
    reviewers:
      - "crgee1" # Chris
      - "stanlp1" # Stanley
